src/pages/Login.tsx

- Added new icons for email and password fields.
- Implemented password visibility toggle feature.
- Updated error message for sign-in failure.
- Redesigned layout with a logo and welcome message.
- Introduced a "Remember me" checkbox and a "Forgot password?" link.
- Added Google sign-in button and animated floating cubes for visual appeal.
- Improved overall styling and responsiveness of the login form.

Enhance Login component with improved UI and functionality

---

src/components/builder/Canvas.tsx
src/index.css

- Introduced floating animation for draggable components in the Canvas.
- Added cursor animation to enhance user interaction.
- Updated the placeholder text to guide users in building their dashboard with a more engaging layout.

Add animated components to Canvas and new CSS animations

---

src/pages/Settings.tsx

- Changed the data model from AccountSettings to CompanySettings.
- Updated API functions to fetch and update company settings instead of account settings.
- Adjusted the loadSettings function to utilize fetchCompanySettings for data retrieval.
This change aligns the Settings component with the new company-focused data structure.

Refactor Settings component to use CompanySettings and update API calls

---

src/services/api/database.ts

- Added user authentication checks to ensure only authenticated users can access their respective tables.
- Implemented retrieval of the current user's account ID from the 'user_accounts' table for all relevant database operations.
- Updated `checkTableExists`, `addToMasterTables`, `fetchTables`, and `getTableData` functions to filter data based on the user's account ID.
- Improved error handling and logging for better debugging and user feedback.
These changes ensure that database operations are securely tied to user accounts, enhancing data integrity and access control.

Enhance database API functions to support account-based access

---

src/components/builder/Canvas.tsx
src/services/api/canvasComponents.ts

- Updated the Canvas component to handle initialization errors with user feedback.
- Added state management for error handling in the Canvas component.
- Modified `saveCanvasComponents` and `fetchCanvasComponents` API functions to include user authentication checks and filter data by the user's company ID.
- Improved error handling to ensure only authenticated users can access their respective canvas components.
These changes enhance user experience and ensure data integrity by tying canvas operations to user accounts.

Enhance Canvas component and API functions for account-based access

---

src/App.tsx
src/components/layout/OnboardingWrapper.tsx
src/components/layout/Sidebar.tsx
src/components/modals/OnboardingModal.tsx
src/services/api/canvas.ts
src/services/api/canvasComponents.ts
src/services/api/settings.ts
src/store/useCanvasesStore.ts

- Wrapped the main application in an OnboardingWrapper component to manage onboarding flows.
- Updated Sidebar to fetch canvases on mount and handle canvas selection with error handling.
- Refactored canvas management in the store to include loading states and error handling for fetching, adding, deleting, and renaming canvases.
- Improved API functions for saving and fetching canvas components to streamline data handling.
These changes improve user experience by ensuring a smoother onboarding process and robust canvas management.

Integrate OnboardingWrapper and enhance Sidebar functionality

---

src/components/layout/OnboardingWrapper.tsx

- Integrated useAuth context to manage user state within OnboardingWrapper.
- Modified canvas initialization logic to only fetch canvases if a user is authenticated.
- Updated onboarding modal display conditions to ensure it only shows for authenticated users with no canvases.
These changes enhance the onboarding experience by ensuring that only authenticated users are guided through the onboarding process.

Refactor OnboardingWrapper to incorporate user authentication checks

---

src/services/api/canvas.ts

- Removed unnecessary console log for fetching canvases.
- Added conditional logging to only display the number of canvases found if data exists.
- Ensured that an empty array is returned if no canvases are fetched, maintaining consistent return values.
These changes enhance the clarity of logs and ensure better handling of scenarios where no canvases are available.

Refactor canvas fetching logic to improve logging and error handling

---

src/services/api/canvas.ts
src/store/useCanvasesStore.ts

- Removed unnecessary console logs in the canvas fetching process to streamline the code.
- Updated the fetchUserCanvases function to conditionally log the number of canvases found only if data exists.
- Enhanced the useCanvasesStore to eliminate redundant logging during canvas fetching.
These changes enhance code clarity and maintainability while ensuring consistent behavior when no canvases are available.

Refactor canvas fetching and store logic to improve logging

---

package-lock.json
package.json
src/contexts/AuthContext.tsx
src/types/usetiful.d.ts
src/utils/usetiful.ts

- Added "usetiful-sdk" version 0.1.3 to package.json and package-lock.json.
- Integrated initialization of Usetiful in AuthContext to trigger when a user logs in.
These changes enhance user experience by enabling Usetiful's features upon authentication.

Add usetiful-sdk dependency and initialize on user login

---

src/components/common/RowDetailsPanel.tsx

- Added state management for editing selected row data within RowDetailsPanel.
- Implemented handleEdit and handleSave functions to allow users to modify and save row details.
- Updated UI to toggle between view and edit modes, providing a more interactive experience.
- Integrated API call to save updated row data to the database.
These changes improve user interaction by enabling direct editing of row details, enhancing the overall functionality of the RowDetailsPanel.

Enhance RowDetailsPanel with editing functionality

---

src/components/users/UserForm.tsx
src/pages/UserManagement.tsx
src/services/api/users.ts

- Updated UserForm to include password input with validation for required and minimum length.
- Modified onSubmit prop to accept password alongside user data.
- Enhanced error handling to display submission errors in the UI.
- Updated createUser API function to handle user registration with password, including error management for existing users.
- Adjusted UserManagement component to align with new user data structure.
These changes improve user account creation by ensuring secure password handling and providing better feedback during the user registration process.

Enhance UserForm and User Management with Password Handling

---

src/services/api/users.ts

- Updated fetchUsers function to call a secure RPC method for fetching user accounts along with their emails.
- Removed the previous method of fetching user accounts and mapping the authenticated user's email, simplifying the data retrieval process.
- Enhanced code clarity with updated comments to reflect the new approach.
These changes improve data security and streamline the user account fetching process.

Refactor fetchUsers to utilize secure RPC for user accounts retrieval

---

src/components/layout/Sidebar.tsx

- Added supabase client integration to fetch user account details based on the authenticated user.
- Renamed function to loadAuthenticatedUser for clarity and updated error handling messages.
- Adjusted useEffect dependencies to ensure user data is loaded when the user state changes.
These changes improve user experience by ensuring the Sidebar displays the correct user information.

Enhance Sidebar component to load authenticated user data

---

src/App.tsx
src/components/layout/Sidebar.tsx

- Integrated user role-based access control by fetching authenticated user data from Supabase.
- Updated App component to restrict access to certain pages based on user roles.
- Modified Sidebar to conditionally display menu items and settings access for creators only.
- Improved error handling and user experience during data fetching.
These changes ensure that the application properly manages user permissions and enhances the overall user experience.

Enhance authentication and authorization in App and Sidebar components

---

src/index.css
src/pages/Builder.tsx

- Added new CSS animations for loading indicators, including 'ping-slow', 'float-1', and 'float-2'.
- Updated the Builder component to incorporate animated background cubes and a pulsating logo during the loading state.
- Improved the loading UI with a more engaging design, enhancing user experience while fetching dashboard data.
These changes provide a visually appealing loading experience, making the application feel more dynamic and responsive.

Enhance loading experience in Builder component with new animations

---

src/components/builder/DraggableComponent.tsx
src/components/builder/components/ChartComponent/index.tsx

- Wrapped TableComponent and LineChart in divs with consistent styling, including background color and padding, to enhance visual appeal.
- Updated class names and styles for better alignment and spacing in editor mode.
- Improved overall layout and responsiveness of components, ensuring a more polished user interface.
These changes contribute to a more cohesive design across the Builder component, enhancing user experience.

Refactor Draggable and Chart Components for Improved UI Consistency

---

src/components/builder/TableComponent.tsx

- Added rounded corners to the table container and header cells for a more polished look.
- Updated table header and action column with border styles for better visual separation.
- Implemented conditional styling for the last row to enhance the table's appearance.
These changes improve the overall user interface and visual consistency of the TableComponent.

Enhance TableComponent with improved styling and layout

---

src/components/builder/Canvas.tsx
src/components/builder/DraggableComponent.tsx

- Added a reference to the canvas in the Canvas component to manage component positioning.
- Implemented a constrainPosition function to ensure components are dropped within canvas bounds.
- Updated the drop logic to use the new position constraints when adding or moving components.
- Enhanced the DraggableComponent to constrain its size during resizing, ensuring it remains within the canvas area.
These changes improve the user experience by preventing components from being placed or resized outside the designated canvas area.

Enhance Canvas and DraggableComponent with position and size constraints

---

src/components/builder/Canvas.tsx
src/components/builder/DraggableComponent.tsx
src/components/builder/Guidelines.tsx
src/index.css
src/store/useGuidelinesStore.ts

- Introduced visual guidelines for component alignment within the Canvas.
- Implemented logic to calculate and display vertical and horizontal guidelines based on component positions and canvas edges.
- Added CSS styles for guideline visualization.
- Enhanced DraggableComponent to show/hide guidelines during drag operations.
These changes improve the user experience by providing helpful alignment aids while positioning components on the canvas.

Add guidelines feature to Canvas component

---

src/components/database/TableBuilder.tsx
src/services/api/database.ts
src/utils/database.ts

- Added account ID fetching from Supabase upon component mount to prefix table names.
- Implemented validation for table names to ensure they start with a letter and contain only valid characters.
- Updated the table creation logic to use the normalized table name with the account ID prefix.
- Improved user interface by displaying the account ID as a read-only field in the form.
These changes enhance data integrity and user experience by ensuring valid table names and providing context for table creation.

Enhance TableBuilder with account ID handling and table name validation

---

package-lock.json
package.json
src/components/database/PostgresConnectionModal.tsx
src/components/database/PostgresConnections.tsx
src/pages/Resources.tsx

- Added bcrypt and its TypeScript definitions to package.json and package-lock.json for password hashing functionality.
- Introduced PostgresConnections component in Resources page to manage PostgreSQL connections.
- Implemented state management for displaying the PostgresConnections view based on user interaction.
These changes improve security and extend the functionality of the Resources component by integrating PostgreSQL connection management.

Update dependencies and enhance Resources component

---

src/pages/Resources.tsx

- Added optional 'comingSoon' property to ResourceCard interface.
- Updated PostgreSQL icon to use an image source instead of a component.
- Marked certain resources as 'coming soon' with visual indicators.
- Adjusted click handling to prevent interaction with 'coming soon' resources.
These changes improve user experience by clearly indicating upcoming resources and enhancing the visual representation of the PostgreSQL resource.

Enhance Resources component with 'comingSoon' feature and icon updates

---

README.md

- Added a new section detailing the database_auth_settings table structure.
- Included fields such as id, created_at, accounts_id, connection_name, host, port, db_name, db_username, and db_password.
This update enhances documentation by providing clear information on database authentication settings for users.

Update README.md to include new database_auth_settings section

---

src/components/database/ExternalPostgresTables.tsx
src/components/database/PostgresConnectionModal.tsx
src/components/database/PostgresConnections.tsx
supabase/.gitignore
supabase/config.toml
supabase/functions/_shared/cors.ts
supabase/functions/listPostgresTables/index.ts

- Introduced host validation in PostgresConnectionModal to clean input by removing prefixes.
- Updated the handleSubmit function to use the cleaned host value when inserting connection data.
- Modified PostgresConnections component to include port and db_password in the connection details.
- Added functionality to handle connection clicks, allowing users to view external PostgreSQL tables.
- Improved UI interactions with hover effects on connection items.
These changes enhance the user experience by ensuring cleaner data submission and providing better management of PostgreSQL connections.

Enhance Postgres connection management and validation

---

src/pages/Resources.tsx

- Added MongoDB, MySQL, and Google Sheets to the Resources list with icons and descriptions.
- Marked these resources as 'coming soon' to indicate future availability.
These updates expand the available resources and improve user awareness of upcoming features.

Enhance Resources component with additional database options

---

src/components/builder/ComponentPalette.tsx
src/pages/Builder.tsx

- Updated the styling of DraggableComponent for better spacing and text truncation.
- Reduced icon sizes in ComponentPalette for a more compact design.
- Adjusted the width and padding of the ComponentPalette in Builder for a cleaner layout.
- Removed unnecessary mobile overlay code to simplify the component structure.
These changes enhance the user interface by improving component spacing and overall layout consistency.

Refactor ComponentPalette and Builder layout for improved UI

---

package-lock.json
package.json
src/components/builder/Canvas.tsx
src/components/builder/ComponentPalette.tsx
src/components/builder/DraggableComponent.tsx
src/components/builder/KanbanComponent.tsx
src/components/builder/PropertiesPanel.tsx
src/components/builder/components/KanbanComponent/index.tsx
src/components/builder/components/KanbanComponent/properties.tsx

- Added Kanban component with sample data structure for managing tasks.
- Integrated Kanban support in DraggableComponent and PropertiesPanel for seamless user interaction.
- Updated package dependencies to include @dnd-kit libraries for improved drag-and-drop functionality.
- Added types for react-beautiful-dnd to ensure compatibility with existing components.
These changes enhance the application's capability to manage tasks visually and improve the overall user experience.

Enhance Kanban functionality and update dependencies

---

src/components/builder/DraggableComponent.tsx
src/components/builder/TableComponent.tsx
src/components/builder/components/TableComponent/properties.tsx

- Added columnVisibility prop to TableComponent for dynamic column display.
- Implemented showActions prop to conditionally render action buttons.
- Updated DraggableComponent to pass columnVisibility to TableComponent.
- Enhanced TableProperties to manage column visibility state and toggle functionality.
These changes improve the flexibility and usability of the table component, allowing for better data presentation and user interaction.

Enhance TableComponent with column visibility and action handling

---

README.md

- Added VITE_DEEPSEEK_API_NAME and VITE_DEEPSEEK_API_KEY to the Environment Variables section.
This change provides necessary configuration details for integrating the DeepSeek API into the application.

Update README.md to include DeepSeek API environment variables
